# Generated by Django 2.2 on 2019-10-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheer_app', '0003_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='achievement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
